language: node_js
node_js: stable
before_script:
- bower install --silent
addons:
  sauce_connect: true
script:
- npm run lint
- polymer test --plugin sauce --job-name "arc-chrome-settings:${TRAVIS_BRANCH}" --build-number=${TRAVIS_BUILD_NUMBER}
cache:
  directories:
  - node_modules
branches:
  only:
  - stage
  - develop
after_success:
- node tasks/ci.js
env:
  global:
  - secure: q1Fi9SCQVvRyD9Gg114+9wGY7/VN9ikLHgKhCqnROS00phlO+nAybB4H8MmsYdrA6oeLYY7yCpBPIitXVrZ0+7VaigqozZsiEmAV6LujPZD8VxqJ2aU5ofgUhUoh/HDZi2mhCj9OWrodQN70qVo9jMpA5o3f7qSyQtdsImc2nQ2auaR9WvLYOf83/u5/SN23K+gL7QVCYinsThm6iqwHL3EWcobaSw+Sksle2xhbb9IPO7QqDoFrZ/ZIxfNsXae661uKOg9V+8SSB98PfezM8Bogj3DUok4/RwPuVH8Ybs1ZqBeLSgOcSJ4rweZoaLBEj+ked+GVhrUPCuVWUT8NKzMYMe+W29bciz22Pd8ftsJdO5V43zAlc7gSHEME8/azf7GxxocbIRzJZcj0AABcsPKnj4DkhJCfmzZrS8v6bTPZMdmced5zryqF+bZulDA2CufhQZ7zVKmo5uj9lj038u8uCyuTnGlu2JUAyMYPpU+wflZzAMzaYZAoW+blImVMWqNQl+bKIwmrvaN4DyEjk14r0hxyTR1DMjHuGTL2tmaxJbiis8FZELU6TLX54lOFDLjU3hW9HqiRTwjW7KBIR+a1eDva0PyDpFckFbhrlcqHoBKSBPKsTVjUZOrzlJ482Lv3/8DXpnQ0/NhTEg4LG6QMkeob4kAsowqkPlyF2Ug=
  - secure: OqrLeG9maEe9soGz8lsaJDLEwC6c3o67vxs8mvh7/izKNu9i6y1JB0h/fEt6DS0DRJ+NycyYDiZcHHsua7qqk2v9E2k6YLviXic6cgsDLKTnefNkU2QhSAfxLAixVMbywtUYkaZconf9+UUlpK0sQAIel6TJDy12RA1okZwxZebY7NYLPya7ikeChBi3YQfmOIqRsjBWzfE/u+BAZfV78GpjSBYrTag+b/fMSONrrzsFyO26QTEw1MfRJ0f/xbOpmpbufELoDBvI4pz4J9eI1Pq4jl7iNZxTFt41wdxfwkuFse5asngznGjP4BVrJ91qKqFIrcpygSd8z1s+HYaSnjSrklmuY95t+CPHVEE4V5sV28QfsoVLvh1ln8Yo0O/IIX6NdL66tYXR4LBo27Gta46RkPG8rIkj5M37XjsPqor8MuIYIX6GcBlcHWtyujzbFc0Khnc4sHAAU3KXGZp74ZvQgOnv7UaoA/0tG8R60Mkr12Wf4qPtQJ3DgKrYOYcQOdGZl2xLIDI5/qmooUHBz+nNSPpd3U/JdZoJsiD77FraZUuHG2LzAGrgkCcTTnljRKYd1qRCWeaXUI2pJTESBXhVeL35TDGGzUqTBJtcAyop6jb1/EsLpfmsuktHrGNZCG2/B+sAm4VAUiOgxuBDDzNw+JbSnhk+zrhJTLunmjs=
